### ISSUE TITLE
Dynamically detect kraken's import path

### ISSUE THREAD

**Issue by synackd** [kraken-hpc/kraken#184]
When compiling templates for u-root, import paths in the compiled templates are changed from using packages in the main kraken source tree (i.e. `github.com/hpc/kraken/...` to using the similar packages that are included with the generated sources (i.e. `github.com/hpc/kraken/build/u-root/...`.

This is currently hard-coded, and this should ideally be detected dynamically.

**Comment by jlowellwofford** [comment]
With the new model for building, the u-root source tree is no longer necessary and this becomes irrelevant.
